### ISSUE TITLE
Problems with `pam_loginuid` with Sway

### ISSUE THREAD

**Issue by paulusel** [coastalwhite/lemurs#126]
Hello,

When I try to login with sway, I get this error.

`pam_loginuid(system-login:session): set_loginuid failed`
`pam_loginuid(system-login:session): Error writing /proc/self/loginuid: Operation not permitted`

I am in seat group. while previewing, it is okay and with sddm I can login just fine.
I am using stock config file from extra directory of the repo.

**Comment by paulusel** [comment]
I am on Arch Linux and got lemurs-git from AUR. Built with normal commands locally. 

- rustc 1.67.1
- cargo 1.67.1

Stable rust toolchain from arch repos.

**Comment by coastalwhite** [comment]
Heya!

Sorry, this is probably the same as a standing bug with the `XDG_SESSION_ID` being wrongfully set. This bug was already fixed on the `develop` branch, and a new version has just been released which also contains the fix.

Would you mind trying out the new version and let me know how that goes?

**Comment by paulusel** [comment]
Unfortunately the issue persists in version **0.3.1.r1.gd84deac-1**.  I just did git pull and rebuilt but same thing. And there's only master branch on the repo.

**Comment by paulusel** [comment]
I'm using Archlinux and installed lemurs from aur. And yes it looks very much like #103 specially around [here](https://github.com/coastalwhite/lemurs/issues/103#issuecomment-1457602522).

**Comment by paulusel** [comment]
Ha, it appears to be solved in **0.3.1.r3.g60fda2a-1** version now. I just did login. 

But gnome key ring wasn't unlocked at login. Is that normal? @coastalwhite

**Comment by paulusel** [comment]
Well, I retried couple of time just to make sure everything is okay. And it seems everything is okay. I found workaround for workaround in ArchWiki [here](https://wiki.archlinux.org/title/GNOME/Keyring#Using_the_keyring).

This issue can be closed, I guess.

**Comment by coastalwhite** [comment]
Good to hear!

> But gnome key ring wasn't unlocked at login. Is that normal? @coastalwhite 

That is sadly a side effect of having a default setup suited for most Linux distributions. The workaround you found is the proper way to do it. I will see whether I can add a part somewhere in the docs about this.

Closing this issue.
